services:
  task-mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-task
    volumes:
      - task-volume:/data/taskdb

  account-mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-account
    volumes:
      - account-volume:/data/accountdb

  config:
    image: agomezuc96/config:latest
    restart: always
    container_name: config
    environment:
      - LOGSTASH_DESTINATION=logstash:25826
      - LOGSTASH_ENABLED=false

  registry-service:
    image: agomezuc96/registry-service:latest
    restart: always
    container_name: registry-service
    environment:
      - LOGSTASH_DESTINATION=logstash:25826
      - LOGSTASH_ENABLED=false
    ports:
      - 8761:8761
    depends_on:
      - config

  task-service:
    image: agomezuc96/task-service:latest
    restart: always
    container_name: task-service
    environment:
      - LOGSTASH_DESTINATION=logstash:25826
      - LOGSTASH_ENABLED=false
    ports:
      - 8080:8080
    depends_on:
      - task-mongodb
      - registry-service
      - config
  account-service:
    image: agomezuc96/account-service:latest
    restart: always
    container_name: account-service
    environment:
      - LOGSTASH_DESTINATION=logstash:25826
      - LOGSTASH_ENABLED=false
    ports:
      - 8082:8082
    depends_on:
      - account-mongodb
      - registry-service
      - config
volumes:
  task-volume:
  account-volume:

